//
// Agent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct Agent: Codable, JSONEncodable, Hashable {

    static let accountIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let symbolRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let headquartersRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var accountId: String
    public var symbol: String
    /** The headquarters of the agent. */
    public var headquarters: String
    /** The number of credits the agent has available. Credits can be negative if funds have been overdrawn. */
    public var credits: Int

    public init(accountId: String, symbol: String, headquarters: String, credits: Int) {
        self.accountId = accountId
        self.symbol = symbol
        self.headquarters = headquarters
        self.credits = credits
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accountId
        case symbol
        case headquarters
        case credits
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(accountId, forKey: .accountId)
        try container.encode(symbol, forKey: .symbol)
        try container.encode(headquarters, forKey: .headquarters)
        try container.encode(credits, forKey: .credits)
    }
}

