//
// ContractTerms.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ContractTerms: Codable, JSONEncodable, Hashable {

    /** The deadline for the contract. */
    public var deadline: Date
    public var payment: ContractPayment
    public var deliver: [ContractDeliverGood]?

    public init(deadline: Date, payment: ContractPayment, deliver: [ContractDeliverGood]? = nil) {
        self.deadline = deadline
        self.payment = payment
        self.deliver = deliver
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case deadline
        case payment
        case deliver
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(deadline, forKey: .deadline)
        try container.encode(payment, forKey: .payment)
        try container.encodeIfPresent(deliver, forKey: .deliver)
    }
}

