//
// ContractPayment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ContractPayment: Codable, JSONEncodable, Hashable {

    /** The amount of credits received up front for accepting the contract. */
    public var onAccepted: Int
    /** The amount of credits received when the contract is fulfilled. */
    public var onFulfilled: Int

    public init(onAccepted: Int, onFulfilled: Int) {
        self.onAccepted = onAccepted
        self.onFulfilled = onFulfilled
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case onAccepted
        case onFulfilled
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(onAccepted, forKey: .onAccepted)
        try container.encode(onFulfilled, forKey: .onFulfilled)
    }
}

