//
// DeliverContract200ResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DeliverContract200ResponseData: Codable, JSONEncodable, Hashable {

    public var contract: Contract
    public var cargo: ShipCargo

    public init(contract: Contract, cargo: ShipCargo) {
        self.contract = contract
        self.cargo = cargo
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case contract
        case cargo
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(contract, forKey: .contract)
        try container.encode(cargo, forKey: .cargo)
    }
}

