//
// ExtractionYield.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ExtractionYield: Codable, JSONEncodable, Hashable {

    static let symbolRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var symbol: String
    /** The number of units extracted that were placed into the ship's cargo hold. */
    public var units: Int

    public init(symbol: String, units: Int) {
        self.symbol = symbol
        self.units = units
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case symbol
        case units
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(symbol, forKey: .symbol)
        try container.encode(units, forKey: .units)
    }
}

