//
// Meta.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct Meta: Codable, JSONEncodable, Hashable {

    public var total: Int
    public var page: Int
    public var limit: Int

    public init(total: Int, page: Int, limit: Int) {
        self.total = total
        self.page = page
        self.limit = limit
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case total
        case page
        case limit
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(total, forKey: .total)
        try container.encode(page, forKey: .page)
        try container.encode(limit, forKey: .limit)
    }
}

