//
// NavigateShip200ResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct NavigateShip200ResponseData: Codable, JSONEncodable, Hashable {

    public var fuel: ShipFuel
    public var nav: ShipNav

    public init(fuel: ShipFuel, nav: ShipNav) {
        self.fuel = fuel
        self.nav = nav
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fuel
        case nav
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(fuel, forKey: .fuel)
        try container.encode(nav, forKey: .nav)
    }
}

