//
// PurchaseShip201ResponseData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PurchaseShip201ResponseData: Codable, JSONEncodable, Hashable {

    public var agent: Agent
    public var ship: Ship
    public var transaction: ShipyardTransaction

    public init(agent: Agent, ship: Ship, transaction: ShipyardTransaction) {
        self.agent = agent
        self.ship = ship
        self.transaction = transaction
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case agent
        case ship
        case transaction
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(agent, forKey: .agent)
        try container.encode(ship, forKey: .ship)
        try container.encode(transaction, forKey: .transaction)
    }
}

