//
// ShipRequirements.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The requirements for installation on a ship */
public struct ShipRequirements: Codable, JSONEncodable, Hashable {

    /** The amount of power required from the reactor. */
    public var power: Int?
    /** The number of crew required for operation. */
    public var crew: Int?
    /** The number of module slots required for installation. */
    public var slots: Int?

    public init(power: Int? = nil, crew: Int? = nil, slots: Int? = nil) {
        self.power = power
        self.crew = crew
        self.slots = slots
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case power
        case crew
        case slots
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(power, forKey: .power)
        try container.encodeIfPresent(crew, forKey: .crew)
        try container.encodeIfPresent(slots, forKey: .slots)
    }
}

