//
// ShipNavFlightMode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The ship&#39;s set speed when traveling between waypoints or systems. */
public enum ShipNavFlightMode: String, Codable, CaseIterable {
    case drift = "DRIFT"
    case stealth = "STEALTH"
    case cruise = "CRUISE"
    case burn = "BURN"
}
