//
// ShipNav.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The navigation information of the ship. */
public struct ShipNav: Codable, JSONEncodable, Hashable {

    /** The system symbol of the ship's current location. */
    public var systemSymbol: String
    /** The waypoint symbol of the ship's current location, or if the ship is in-transit, the waypoint symbol of the ship's destination. */
    public var waypointSymbol: String
    public var route: ShipNavRoute
    public var status: ShipNavStatus
    public var flightMode: ShipNavFlightMode

    public init(systemSymbol: String, waypointSymbol: String, route: ShipNavRoute, status: ShipNavStatus, flightMode: ShipNavFlightMode) {
        self.systemSymbol = systemSymbol
        self.waypointSymbol = waypointSymbol
        self.route = route
        self.status = status
        self.flightMode = flightMode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case systemSymbol
        case waypointSymbol
        case route
        case status
        case flightMode
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(systemSymbol, forKey: .systemSymbol)
        try container.encode(waypointSymbol, forKey: .waypointSymbol)
        try container.encode(route, forKey: .route)
        try container.encode(status, forKey: .status)
        try container.encode(flightMode, forKey: .flightMode)
    }
}

