//
// ShipNavStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The current status of the ship */
public enum ShipNavStatus: String, Codable, CaseIterable {
    case inTransit = "IN_TRANSIT"
    case inOrbit = "IN_ORBIT"
    case docked = "DOCKED"
}
