//
// ShipCargoItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The type of cargo item and the number of units. */
public struct ShipCargoItem: Codable, JSONEncodable, Hashable {

    static let unitsRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    /** The unique identifier of the cargo item type. */
    public var symbol: String
    /** The name of the cargo item type. */
    public var name: String
    /** The description of the cargo item type. */
    public var description: String
    /** The number of units of the cargo item. */
    public var units: Int

    public init(symbol: String, name: String, description: String, units: Int) {
        self.symbol = symbol
        self.name = name
        self.description = description
        self.units = units
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case symbol
        case name
        case description
        case units
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(symbol, forKey: .symbol)
        try container.encode(name, forKey: .name)
        try container.encode(description, forKey: .description)
        try container.encode(units, forKey: .units)
    }
}

