//
// ShipRegistration.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The public registration information of the ship */
public struct ShipRegistration: Codable, JSONEncodable, Hashable {

    static let nameRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let factionSymbolRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    /** The agent's registered name of the ship */
    public var name: String
    /** The symbol of the faction the ship is registered with */
    public var factionSymbol: String
    public var role: ShipRole

    public init(name: String, factionSymbol: String, role: ShipRole) {
        self.name = name
        self.factionSymbol = factionSymbol
        self.role = role
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case factionSymbol
        case role
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(factionSymbol, forKey: .factionSymbol)
        try container.encode(role, forKey: .role)
    }
}

