//
// ShipType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public enum ShipType: String, Codable, CaseIterable {
    case probe = "SHIP_PROBE"
    case miningDrone = "SHIP_MINING_DRONE"
    case interceptor = "SHIP_INTERCEPTOR"
    case lightHauler = "SHIP_LIGHT_HAULER"
    case commandFrigate = "SHIP_COMMAND_FRIGATE"
    case explorer = "SHIP_EXPLORER"
    case heavyFreighter = "SHIP_HEAVY_FREIGHTER"
    case lightShuttle = "SHIP_LIGHT_SHUTTLE"
    case oreHound = "SHIP_ORE_HOUND"
    case refiningFreighter = "SHIP_REFINING_FREIGHTER"
}
