//
// ShipReactor.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The reactor of the ship. The reactor is responsible for powering the ship&#39;s systems and weapons. */
public struct ShipReactor: Codable, JSONEncodable, Hashable {

    public enum Symbol: String, Codable, CaseIterable {
        case solarI = "REACTOR_SOLAR_I"
        case fusionI = "REACTOR_FUSION_I"
        case fissionI = "REACTOR_FISSION_I"
        case chemicalI = "REACTOR_CHEMICAL_I"
        case antimatterI = "REACTOR_ANTIMATTER_I"
    }
    static let conditionRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 100, exclusiveMaximum: false, multipleOf: nil)
    static let powerOutputRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var symbol: Symbol
    public var name: String
    public var description: String
    /** Condition is a range of 0 to 100 where 0 is completely worn out and 100 is brand new. */
    public var condition: Int?
    public var powerOutput: Int
    public var requirements: ShipRequirements

    public init(symbol: Symbol, name: String, description: String, condition: Int? = nil, powerOutput: Int, requirements: ShipRequirements) {
        self.symbol = symbol
        self.name = name
        self.description = description
        self.condition = condition
        self.powerOutput = powerOutput
        self.requirements = requirements
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case symbol
        case name
        case description
        case condition
        case powerOutput
        case requirements
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(symbol, forKey: .symbol)
        try container.encode(name, forKey: .name)
        try container.encode(description, forKey: .description)
        try container.encodeIfPresent(condition, forKey: .condition)
        try container.encode(powerOutput, forKey: .powerOutput)
        try container.encode(requirements, forKey: .requirements)
    }
}

