//
// ShipRole.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The registered role of the ship */
public enum ShipRole: String, Codable, CaseIterable {
    case fabricator = "FABRICATOR"
    case harvester = "HARVESTER"
    case hauler = "HAULER"
    case interceptor = "INTERCEPTOR"
    case excavator = "EXCAVATOR"
    case transport = "TRANSPORT"
    case repair = "REPAIR"
    case surveyor = "SURVEYOR"
    case command = "COMMAND"
    case carrier = "CARRIER"
    case patrol = "PATROL"
    case satellite = "SATELLITE"
    case explorer = "EXPLORER"
    case refinery = "REFINERY"
}
