//
// ShipCargo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ShipCargo: Codable, JSONEncodable, Hashable {

    static let capacityRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    static let unitsRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    /** The max number of items that can be stored in the cargo hold. */
    public var capacity: Int
    /** The number of items currently stored in the cargo hold. */
    public var units: Int
    /** The items currently in the cargo hold. */
    public var inventory: [ShipCargoItem]

    public init(capacity: Int, units: Int, inventory: [ShipCargoItem]) {
        self.capacity = capacity
        self.units = units
        self.inventory = inventory
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case capacity
        case units
        case inventory
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(capacity, forKey: .capacity)
        try container.encode(units, forKey: .units)
        try container.encode(inventory, forKey: .inventory)
    }
}

