//
// SystemWaypoint.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SystemWaypoint: Codable, JSONEncodable, Hashable {

    public var symbol: String
    public var type: WaypointType
    public var x: Int
    public var y: Int

    public init(symbol: String, type: WaypointType, x: Int, y: Int) {
        self.symbol = symbol
        self.type = type
        self.x = x
        self.y = y
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case symbol
        case type
        case x
        case y
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(symbol, forKey: .symbol)
        try container.encode(type, forKey: .type)
        try container.encode(x, forKey: .x)
        try container.encode(y, forKey: .y)
    }
}

