//
// SystemType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The type of waypoint. */
public enum SystemType: String, Codable, CaseIterable {
    case neutronStar = "NEUTRON_STAR"
    case redStar = "RED_STAR"
    case orangeStar = "ORANGE_STAR"
    case blueStar = "BLUE_STAR"
    case youngStar = "YOUNG_STAR"
    case whiteDwarf = "WHITE_DWARF"
    case blackHole = "BLACK_HOLE"
    case hypergiant = "HYPERGIANT"
    case nebula = "NEBULA"
    case unstable = "UNSTABLE"
}
