//
// WaypointType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The type of waypoint. */
public enum WaypointType: String, Codable, CaseIterable {
    case planet = "PLANET"
    case gasGiant = "GAS_GIANT"
    case moon = "MOON"
    case orbitalStation = "ORBITAL_STATION"
    case jumpGate = "JUMP_GATE"
    case asteroidField = "ASTEROID_FIELD"
    case nebula = "NEBULA"
    case debrisField = "DEBRIS_FIELD"
    case gravityWell = "GRAVITY_WELL"
}
